name: flutter_shop
description: flutter电子商城.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^4.0.2+3
  flutter_easyrefresh: ^2.1.8
  fluttertoast: ^7.1.6
  flutter_html: ^1.1.0
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/head.jpeg
    - assets/images/head_bg.png
